version: '3.3'
services:
  backend:
    build: ./django_project
    ports:
    - "8080:8080"
    volumes:
    - "./django_project/:/code"
    command: sh -c "poetry run python manage.py migrate
                    && poetry run python manage.py runserver 0.0.0.0:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: kartoza/postgis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
