# Generated by Django 3.2 on 2021-04-16 17:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210416_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('num', models.IntegerField(verbose_name='Номер раунда в игре')),
                ('score', models.IntegerField(verbose_name='Очки')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Время начала раунда')),
                ('date_end', models.DateTimeField(verbose_name='Время окончания раунда')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game', verbose_name='Игра')),
                ('random_point', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.point', verbose_name='Рандомная точка')),
            ],
        ),
    ]
