# Generated by Django 3.2 on 2021-04-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210416_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='random_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds', to='game.point', verbose_name='Рандомная точка'),
        ),
    ]
