# Generated by Django 3.2 on 2021-04-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_round_random_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='num',
            field=models.IntegerField(default=None, null=True, verbose_name='Номер раунда в игре'),
        ),
    ]
