# Generated by Django 3.2 on 2021-04-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_game_game_over'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_over',
            new_name='is_over',
        ),
    ]
