# Generated by Django 3.2 on 2021-04-20 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_category_rounds_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.ManyToManyField(related_name='liked_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
