# Generated by Django 3.2 on 2021-04-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20210420_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='score',
            field=models.IntegerField(default=None, null=True, verbose_name='Очки'),
        ),
    ]
