# Generated by Django 3.2 on 2021-04-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_round_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='score',
            field=models.IntegerField(default=0, null=True, verbose_name='Очки'),
        ),
    ]
