# Generated by Django 3.2 on 2021-04-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_game_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end_date',
        ),
    ]
