# Generated by Django 3.2 on 2021-04-20 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_game_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_score',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
